/**
 * @author WMXPY
 * @overview generated by ghoti-cli
 * @fileoverview Component set ComponentGhotiRow
 */

import * as React from 'react';
import { Card } from './card';

export type RowProps = {
    readonly row: any;
    readonly update: (row: any) => void;
    readonly open: (component: JSX.Element) => void;
    readonly close: () => void;
};

export class Row extends React.Component<RowProps> {

    public render() {
        return (<div className="inner-row-container">
            <div className="row-top">
                <div className="info">{this.props.row.name}</div>
            </div>
            <div className="row-bottom">
                {this.props.row.cards.map((card: any, index: number) => {
                    return <Card card={card} key={index}></Card>;
                })}
                {/* <CardNew onClick={() => {
                    let name: string = "";
                    let url: string = "";
                    this.props.open(
                        <div>
                            <Input label="Name" onChange={(value) => name = value}></Input>
                            <Input label="URL" onChange={(value) => url = value}></Input>
                            <button onClick={() => {
                                const row = this.props.row;
                                row.cards.push({
                                    name,
                                    url,
                                });
                                this.props.update(row);
                                this.props.close();
                            }}>ADD</button>
                        </div>,
                    );
                }}></CardNew> */}
            </div>
        </div>);
    }
}
