/**
 * @author WMXPY
 * @overview generated by ghoti-cli
 * @fileoverview Component set ComponentGhotiCard
 */

import * as React from 'react';

export interface IProps {

}

export interface IState {

}

class ComponentGhotiCard extends React.Component<IProps, IState> {
    public constructor(props) {
        super(props);
    }

    public render() {
        return (<div>
            <span>Hello, ComponentGhotiCard!</span>
        </div>);
    }
}

export default ComponentGhotiCard;
