/**
 * @author WMXPY
 * @overview generated by ghoti-cli
 * @fileoverview Component set ComponentGhotiCard-new
 */

import * as React from 'react';

export interface IProps {
    onClick: () => void;
}

export interface IState {

}

class ComponentGhotiCardNew extends React.Component<IProps, IState> {
    public constructor(props) {
        super(props);
    }

    public render() {
        return (<div className="card">
            <button className="info" onClick={this.props.onClick}>+</button>
        </div>);
    }
}

export default ComponentGhotiCardNew;
