/**
 * @author WMXPY
 * @overview generated by ghoti-cli
 * @fileoverview Component set ComponentGhotiCard
 */

import * as React from 'react';
import { ICard } from '../interface';

export interface IProps {
    card: ICard;
}

export interface IState {

}

class ComponentGhotiCard extends React.Component<IProps, IState> {
    public constructor(props) {
        super(props);
    }

    public render() {
        return (<div className="card">
            <button className="link">
                <div className="left">
                    <img src={"https://plus.google.com/_/favicon?domain=" + this.props.card.url} alt={this.props.card.url} width="100px" height="100px" />
                </div>
                <div className="right">{this.props.card.name}</div>
            </button>
        </div>);
    }
}

export default ComponentGhotiCard;
