/**
* @overview generated by ghoti-cli
* @fileoverview components import file
* You should not edit this file by hand
*/

import ComponentGhotiCard from './card.component';
import ComponentGhotiRow from './row.component';
export {
    ComponentGhotiCard as card,
    ComponentGhotiRow as row,
};
