/**
 * @author WMXPY
 * @overview generated by ghoti-cli
 * @fileoverview Component set ComponentGhotiInput
 */

import * as React from 'react';

export type InputProps = {

    readonly label: string;
    readonly onChange: (value: string) => void;
};

export class Input extends React.Component<InputProps> {

    public render() {
        return (<div className="input">
            <div className="left">
                {this.props.label}
            </div>
            <div className="right">
                <input type="text" onChange={(event) => {
                    this.props.onChange(event.target.value);
                }} />
            </div>
        </div>);
    }
}
