/**
 * @author WMXPY
 * @overview generated by ghoti-cli
 * @fileoverview Component set ComponentGhotiInput
 */

import * as React from 'react';

export interface IProps {
    label: string;
    onChange: (value) => void;
}

export interface IState {

}

class ComponentGhotiInput extends React.Component<IProps, IState> {
    public constructor(props) {
        super(props);
    }

    public render() {
        return (<div className="input">
            <div className="left">
                {this.props.label}
            </div>
            <div className="right">
                <input type="text" onChange={(event) => {
                    this.props.onChange(event.target.value);
                }} />
            </div>
        </div>);
    }
}

export default ComponentGhotiInput;
