/**
 * @author WMXPY
 * @overview generated by ghoti-cli
 * @fileoverview Component set ComponentGhotiRow
 */

import * as React from 'react';
import { IRow, ICard, IPage } from '../interface';
import Card from './card.component';
import CardNew from './card-new.component';

export interface IProps {
    row: IRow;
    update: (row: IRow) => void;
    open: (component: JSX.Element) => void;
}

export interface IState {

}

class ComponentGhotiRow extends React.Component<IProps, IState> {
    public constructor(props) {
        super(props);
    }

    public render() {
        return (<div className="inner-row-container">
            <div className="row-top">
                <div className="info">1</div>
            </div>
            <div className="row-bottom">
                {this.props.row.cards.map((card: ICard, index: number) => {
                    return <Card card={card} key={index}></Card>
                })}
                <CardNew onClick={()=>{
                    this.props.open(<div>123</div>);
                    const row = this.props.row;
                    row.cards.push({
                        name: 'google',
                        url: 'live.com',
                    });
                    this.props.update(row);
                }}></CardNew>
            </div>
        </div>);
    }
}

export default ComponentGhotiRow;
