/**
 * @author WMXPY
 * @overview generated by ghoti-cli
 * @fileoverview Component set ComponentGhotiRow
 */

import * as React from 'react';

export interface IProps {

}

export interface IState {

}

class ComponentGhotiRow extends React.Component<IProps, IState> {
    public constructor(props) {
        super(props);
    }

    public render() {
        return (<div className="inner-row-container">
            <div className="row-top">1</div>
            <div className="row-bottom">2</div>
        </div>);
    }
}

export default ComponentGhotiRow;
